#!/bin/bash
#
# fooling around with bash
#
# Copyright (C) 2023-2024 Ronald Jørnsøn
#
# This program is free software: you can redistribute it and/or modify it under \
# the terms of the GNU General Public License as published by the Free Software \
# Foundation, either version 3 of the License, or (at your option) any later \
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT \
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or \
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for \
# more details.
#
# You should have received a copy of the GNU General Public License along \
# with this program. If not, see <https://www.gnu.org/licenses/>.
#
# // SPDX-License-Identifier: GPL-3.0-or-later
#
#############################

package=htop

sudo apt-get install $package >> package_install_results.log

if [ $? -eq 0 ] ; then
  echo "The installation of $package was succesful."
  echo "$package is available here:"
  which $package ; else
  echo "$package failed to install." >> package_install_failure.log
fi


#############################

#command=htop

#if command -v $command ; then
#  echo "$command is available, let's run it!" ; else
#  echo "$command is not available. Installing it!"
#  sudo apt update && sudo apt install htop
#fi

#sleep 2

#$command


#############################

#command=/usr/bin/htop

#if [ -f $command ] ; then
#  echo "$command is available, let's run it!" ; else
#  echo "$command is not available. Installing it!"
#  sudo apt update && sudo apt install htop
#fi

#sleep 3

#$command

#############################

#if [ -f ~/TEST ] ; then
#  echo "The file exists" ; else
#  echo "The file does not exist!"

#############################

#mynum=210

#if [ $mynum -ne 200 ] ; then
#  echo "The condition is true." ; else
#  echo "The condition is false."
#fi

#############################

#name="Ronald Jørnsøn"

#now=$(date)

#echo "Hello $name"

#echo "The system date and time is:"

#echo $now

#echo "Your username is: $USER"

#############################

#now=$(date)
#word=fun

#echo "Linux is $word"
#echo "Videogames are $word"
#echo "Sunny days are $word"
#echo "The system date and time now is:"
#echo $now

##############################

#myname=Ronald
#myage=46

#echo "Hello, my name is $myname."
#echo "I am $myage years old."

#############################

#echo "Hello world!"

#############################
