#!/bin/bash
#
#fooling around with bash


#############################

package=htop

sudo apt install $package

echo "The exit code for the package install is: $?"


#############################

#command=htop

#if command -v $command ; then
#  echo "$command is available, let's run it!" ; else
#  echo "$command is not available. Installing it!"
#  sudo apt update && sudo apt install htop
#fi

#sleep 2

#$command


#############################

#command=/usr/bin/htop

#if [ -f $command ] ; then
#  echo "$command is available, let's run it!" ; else
#  echo "$command is not available. Installing it!"
#  sudo apt update && sudo apt install htop
#fi

#sleep 3

#$command

#############################

#if [ -f ~/TEST ] ; then
#  echo "The file exists" ; else
#  echo "The file does not exist!"

#############################

#mynum=210

#if [ $mynum -ne 200 ] ; then
#  echo "The condition is true." ; else
#  echo "The condition is false."
#fi

#############################

#name="Ronald Jørnsøn"

#now=$(date)

#echo "Hello $name"

#echo "The system date and time is:"

#echo $now

#echo "Your username is: $USER"

#############################

#now=$(date)
#word=fun

#echo "Linux is $word"
#echo "Videogames are $word"
#echo "Sunny days are $word"
#echo "The system date and time now is:"
#echo $now

##############################

#myname=Ronald
#myage=46

#echo "Hello, my name is $myname."
#echo "I am $myage years old."

#############################

#echo "Hello world!"

#############################
